### ISSUE TITLE
 undefined symbol: FLAC__VERSION_STRING

### ISSUE THREAD

**Issue by krinnewitz** [Zuzu-Typ/PyOgg#13]
Under Linux, with PyOgg 0.6.5a1 and libflac 1.3.2 installed, I get the following exception:

```
    from pyogg import OpusFile
  File "/home/kim/.local/lib64/python3.6/site-packages/pyogg/__init__.py", line 11, in <module>
    from . import flac
  File "/home/kim/.local/lib64/python3.6/site-packages/pyogg/flac.py", line 149, in <module>
    libflac.FLAC__VERSION_STRING.restype = c_char_p
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/python-exec/python3.6/python: undefined symbol: FLAC__VERSION_STRING
 ```
This doesn't happen with PyOgg 0.6.4a1, but that is because in versions before 0.6.5a1 libflac wasn't detected at all.

Tested with gentoo and Arch linux. It looks like the definitions in flac.py don't match the content of libflac's format.h

**Comment by Zuzu-Typ** [comment]
Are you using a modified version of libflac? 
The [unmodified format.h](https://github.com/xiph/flac/blob/master/include/FLAC/format.h)  does export this symbol.

**Comment by krinnewitz** [comment]
I am not an expert in this area, but to me it looks like you are referencing FLAC__VERSION_STRING as a function, but it is a constant. The same goes for all the other constants in format.h. Or am I misinterpreting something?
