### ISSUE TITLE
relationship with http://ekyo.nerim.net/software/pyogg/index.html

### ISSUE THREAD

**Issue by sandrotosi** [Zuzu-Typ/PyOgg#15]
Hello,
there exists an old PyOgg implementation at http://ekyo.nerim.net/software/pyogg/index.html (version 1.3) - what's the relationship of this GH project with the historical one? is it a replacement (the version, at least on PyPI, are all older than the old version)? is it a complete replacement/re-implementation? just a coincident same name for the same set of functionalities with no relationship?

thanks

**Comment by Zuzu-Typ** [comment]
Hi sandrotosi,

this GitHub project was created from the ground up. It was originally meant to expand one of my local projects and I decided to publish it later.

On the PyPI, sadly, it's first come, first served and "PyOgg" seemed to be the most fitting name, considering the functionality.

So it's more or less a coincidence.
