### ISSUE TITLE
Problem loading libFLAC on Linux

### ISSUE THREAD

**Issue by gpjt** [Zuzu-Typ/PyOgg#17]
Looks like a great project!  It looks like there's a bug loading the FLAC library on Linux, though -- with a case-sensitive filesystem, it can't load `libFLAC` when it's looking for `libflac`.  I've got it working by replacing this bit of `flac.py`:

    libflac = ExternalLibrary.load("flac", tests = [lambda lib: hasattr(lib, "FLAC__EntropyCodingMethodTypeString")])

....with:

    if sys.platform == "win32":
        libflac = ExternalLibrary.load("flac", tests = [lambda lib: hasattr(lib, "FLAC__EntropyCodingMethodTypeString")])
    else:
        libflac = ExternalLibrary.load("FLAC", tests = [lambda lib: hasattr(lib, "FLAC__EntropyCodingMethodTypeString")])

...but maybe the correct fix would just be to capitalise the library name for all platforms given that win32 is case-insensitive?

**Comment by Zuzu-Typ** [comment]
Thanks for pointing that out.
It should be fixed now.
