### ISSUE TITLE
The Opus libraries weren't found or couldn't be loaded

### ISSUE THREAD

**Issue by LeiYangGH** [Zuzu-Typ/PyOgg#18]
I use anaconda with python3.6 32bit. platform.architecture()=('32bit', 'WindowsPE')
used **pip install pyogg** and successfully installed pyogg-0.6.9a1.
In anaconda3\Lib\site-packages\pyogg\, i can see those dlls.
![image](https://user-images.githubusercontent.com/5386998/58031570-41ec0680-7b53-11e9-9c09-049cd3d092f9.png)

The error:
C:\Users\YANG.LEI\AppData\Local\Continuum\anaconda3\python.exe  
...
    file_ = OpusFile(path)
  File "C:\Users\YANG.LEI\AppData\Local\Continuum\anaconda3\lib\site-packages\pyogg\__init__.py", line 238, in __init__
    raise PyOggError("The Opus libraries weren't found or couldn't be loaded (maybe you're trying to use 64bit libraries with 32bit Python?)")
pyogg.ogg.PyOggError: The Opus libraries weren't found or couldn't be loaded (maybe you're trying to use 64bit libraries with 32bit Python?)

But I'm sure both my python and pyogg is 32bit(when try to install the downloaded 64bit whl it gave me error and exited).

**Comment by Zuzu-Typ** [comment]
I can't quite make out the cause of this issue on first sight.
This error should only occur if no valid opus.dll library could be found.
However, the library is right there, as you pointed out.

I'm not familiar with anaconda unfortunately, but I can't imagine that being the issue.

On my Python 3.7 32bit installation it does detect the DLL flawlessly.

I can only imagine there being a different version of opus on your computer, although I don't see why there should be and on Windows pyogg should be able to find a working candidate by itself, so I really don't know what could be causing this issue.

You could try opening a command prompt in your pyogg installation directory, run python and try the following code:
```
import ctypes
ctypes.CDLL("opus.dll")
```
If this succeeds, it means that the dll can be loaded correctly and the error lies elsewhere.
If an error occurs however, the opus DLL is broken somehow.

**Comment by LeiYangGH** [comment]
Hi Zuzu-Typ, it's very kind of you to reply so soon and detailed!
I tried above code without any errors.

I'm not familiar with python module debugging, but the code snippet
`if libogg:
    PYOGG_OGG_AVAIL = True
else:
    PYOGG_OGG_AVAIL = False`
executed only once, and the result is True.
Could you think of more ways of investigating? I'll try other os/python versions.

**Comment by Zuzu-Typ** [comment]
Thank you very much for the information you provided.
It wasn't opus itself, but rather opusfile causing the issue.
I don't know why, but I must have accidentally distributed some corrupt dlls with pyogg.

I'll push an update as soon as possible.

Sorry for your inconvenience

**Comment by LeiYangGH** [comment]
Hi Zuzu-Typ, really appreciate your quick response!
I downloaded opusfile-v0.9-win32 from http://opus-codec.org/downloads/, and can see part of the dlls in your package, but others such as libFLAC.dll and opusfile.dll are not there. where did you got those files?
![image](https://user-images.githubusercontent.com/5386998/58080547-ff273e80-7be5-11e9-8b73-429ac955213b.png)

**Comment by Zuzu-Typ** [comment]
Getting those libraries without building them yourself is a little difficult.
However, you should be able to simply install the latest version of PyOGG and it should work.
`pip install pyogg --upgrade`

**Comment by LeiYangGH** [comment]
yes. it worked now. thank you!
