### ISSUE TITLE
Wrong arg types of some methods

### ISSUE THREAD

**Issue by gudvinr** [Zuzu-Typ/PyOgg#2]
Some methods like [opus_encoding_ctl](http://opus-codec.org/docs/opus_api-1.1.3/group__opus__encoder.html#ga164cbb0425238961919adf1db67949df) and other `opus_*_ctl` methods take `va_list` as last argument.
But method bindings omits variadic args.

**Comment by Zuzu-Typ** [comment]
It should be fixed now,
I probably overlooked it when translating.
