### ISSUE TITLE
VorbisFile still causes "double free or corruption"

### ISSUE THREAD

**Issue by krisfris** [Zuzu-Typ/PyOgg#20]
Commenting out `vorbis.libvorbisfile.ov_clear(ctypes.byref(vf))` fixed the problem for me. No idea why calling ov_clear causes double free I didn't find another invocation of ov_clear.

**Comment by Zuzu-Typ** [comment]
Hm.. I don't have a Linux system handy to test this myself unfortunately.

I'm currently reworking PyOgg and it's still in a very early stage, but maybe you could try cloning the [future branch](https://github.com/Zuzu-Typ/PyOgg/tree/future) and try if the following code still causes a double free:
```Python
import pyogg
vf = pyogg.VorbisFile("Example.ogg") # replace "Example.ogg" with any ogg vorbis file you have lying around
vf.close()
```
If that does indeed work, please also try the following:
```Python
import pyogg
vf = pyogg.VorbisFile("Example.ogg") # same as before

# maybe it only happens after reading the data..?
data = vf.read() # use read(2048) if the file is rather big and you don't want to wait all day

vf.close()
```
Hopefully that does the trick.

**Comment by krisfris** [comment]
Ok this is what I observed:

In setup.py:91 there is a comma missing before `install_requires`.

Using pyogg by itself results in segfault in `libvorbisfile.ov_fopen` about 90% of the time. Adding a `from openal import *` before using pyogg prevents this problem.

Then, execution continues until it fails with:
```
corrupted size vs. prev_size
Aborted (core dumped)
```

I might be able to look into it at a later time but for now I'm going to use the master branch with the ov_clear line removed and together with openal.

**Comment by Zuzu-Typ** [comment]
Okay, I updated [future](https://github.com/Zuzu-Typ/PyOgg/tree/future).
Please give it another try. There shouldn't be any more issues with open, since I'm not relying on ov_fopen any longer (which is completely broken apparently).

It might not work with PyOpenAL, as it won't be backwards compatible (probably).

Should be a bit more stable now.

**Comment by krisfris** [comment]
The ov_open_callbacks call now segfaults:
```
> python -c 'import pyogg; vf = pyogg.VorbisFile("test.ogg")'
Segmentation fault (core dumped)
> python -c 'from openal import *; import pyogg; vf = pyogg.VorbisFile("test.ogg")'
free(): invalid size
Aborted (core dumped)
```

**Comment by Zuzu-Typ** [comment]
Hmm.
I tried the same on a Linux Mint 19 VM and it worked perfectly fine.

What's your setup?
Which ogg/vorbis libraries are you using?

**Comment by krisfris** [comment]
I'm on ubuntu bionic, using python 3.8.0 (tried 3.6.8 as well). libogg.so.0.8.2, libvorbis.so.0.4.8 and libvorbisfile.so.3.3.7. 
[test.ogg.zip](https://github.com/Zuzu-Typ/PyOgg/files/4050882/test.ogg.zip)

**Comment by Zuzu-Typ** [comment]
Hm. I don't have any problems reading that file.
I'm not sure where you got those libraries from...
The version numbers look like their totally made up somehow.

The latest ogg version is 1.3.4 and as far as my research goes, a version 0.8.2 never existed at all.
As for vorbis, vorbis and vorbisfile can't have different version numbers ar they're part of the same package.
Besides, latest version is 1.3.6, so how can you have 3.3.7?

I'm not as familiar with Linux anymore, but I would recommend you to either build the libs yourself from [here](https://xiph.org/downloads/) or use the binary redistributions from ubuntu (e.g. [this one](https://launchpad.net/ubuntu/+source/libogg/) and [this one](https://launchpad.net/ubuntu/+source/libvorbis/)).

**Comment by krisfris** [comment]
Those are the so files used by ExternalLibrary. Default libraries from ubuntu 18.04. I don't know how those version numbers relate to the library version.
As I said I'm happy with the older version so this issue doesn't really concern me but it might be a problem for others.

**Comment by pimzand** [comment]
Just wanted to mention that the exact same thing happens in both Fedora 31 and Fedora 32.
Fedora 32 was released just this week, and it contains the latest libogg and libvorbis.

**Comment by Zuzu-Typ** [comment]
> Just wanted to mention that the exact same thing happens in both Fedora 31 and Fedora 32.
> Fedora 32 was released just this week, and it contains the latest libogg and libvorbis.

Well, I would love to fix this issue, but as I can't reproduce it and don't really have a lot of info to base my work off of, I see no way to do so.
