### ISSUE TITLE
vorbis_block missing a field

### ISSUE THREAD

**Issue by tyrylu** [Zuzu-Typ/PyOgg#22]
Hello.
When debugging the ogg crashes, i found out that your definition of vorbis block is missing a field, namely after localalloc, at least in libvorbis 1.3.6 there's a totaluse c_long field right after, e. g. the relevant portion of the structure definition should be:
```
                    ("localalloc", c_long),
                    ("totaluse", c_long),
                    ("reap", POINTER(alloc_chain)),
```
No idea why it was not a problem for the bundled libraries under Windows (version/allocator differences?), but the library works under Windows with the added field as well.

**Comment by Zuzu-Typ** [comment]
Hi Lukáš,

thanks a ton! (:
I wouldn't have been able to find this issue.
Hopefully it's the only one responsible for the issues.

Cheers
