### ISSUE TITLE
Windows Libraries

### ISSUE THREAD

**Issue by mattgwwalker** [Zuzu-Typ/PyOgg#28]
Hi Zuzu-Typ,

I've been developing on a Mac up until now, and all has gone well with the Ogg and Opus libraries provided by homebrew.  I'm now testing on Windows.

When I installed PyOgg, I did not get any DLLs in the install, as was indicated in the README.  (I'm using an AWS Instance of Windows Server 2019 for testing.)

Should the libraries have been included with "pip install pyogg"?

I have now compiled DLLs for Ogg and Opus, but I'm finding producing a DLL for OpusFile a challenge.  I see that you contributed a pull request to the official OpusFile repository, but that it wasn't accepted.  How did you get around the OpenSSL issues?

Regards,

Matthew

**Comment by Zuzu-Typ** [comment]
Hi there Matthew,

yes, the Windows release should come with DLLs, unless I forgot to or incorrectly packaged them (which has happened before).
That doesn't seem to be the case for [0.6.14a1](https://github.com/Zuzu-Typ/PyOgg/releases/tag/0.6.14a1) though, as it does contain working DLLs in the wheel (.whl) releases - which should be the ones to be installed using ```pip install pyogg```

Getting all of the DLLs to compile the way you want is not easy.
If I recall correctly, there is a "NoHTTP" build preset for OpusFile, but you may or may not be required to create an opusfile.def file containing all the exported functions (at least I remember doing that).
Sadly it seems that nobody really works on Ogg, Vorbis or Opus anymore.
Thus my changes are highly outdated by now.

Cheers,
--Zuzu_Typ--

**Comment by mattgwwalker** [comment]
Hi again,

Thanks for your very quick reply.

I see that when I ran `pip install pyogg`, version 0.6.13a1 was installed (rather than 14a1).

However I've just learnt something :o)  I needed to have installed "wheel" before I could expect the DLLs to be installed.  Without wheel, pip installs PyOgg fine, and issued a warning that I didn't notice till now "Using legacy setup.py install for PyOgg, since package 'wheel' is not installed."

Once wheel was installed, the DLLs were indeed installed with PyOgg (albeit version 0.6.13a1).

Now, that leaves just one question.  Why did
`pip install git+https://github.com/Zuzu-Typ/PyOgg`
not install version 0.6.14a1?

Can you see what am I doing wrong?

```
pip install git+https://github.com/Zuzu-Typ/PyOgg
Collecting git+https://github.com/Zuzu-Typ/PyOgg
  Cloning https://github.com/Zuzu-Typ/PyOgg to c:\users\administrator\appdata\local\temp\2\pip-req-build-nxb6to46
  Running command git clone -q https://github.com/Zuzu-Typ/PyOgg 'C:\Users\Administrator\AppData\Local\Temp\2\pip-req-build-nxb6to46'
Building wheels for collected packages: PyOgg
  Building wheel for PyOgg (setup.py) ... done
  Created wheel for PyOgg: filename=PyOgg-0.6.13a1-py2.py3-none-any.whl size=35448 sha256=245e3d3ab8a4df461aa6a6c218ff3689c45591ba2a23981c528a2621b7dc1aee
  Stored in directory: C:\Users\Administrator\AppData\Local\Temp\2\pip-ephem-wheel-cache-q1cmt0f0\wheels\5c\fe\cc\ed7e72b13d020b1ec43d6121897da85ec752a41f1ea9701b20
Successfully built PyOgg
Installing collected packages: PyOgg
Successfully installed PyOgg-0.6.13a1



```

**Comment by Zuzu-Typ** [comment]
Don't worry, you're not doing anything wrong (:

I always forget to bump up the version string inside setup.py before uploading the changes to GitHub, thus the version string is incorrect, although it really is PyOgg-0.6.14a1
