### ISSUE TITLE
Encoding libraries bindings

### ISSUE THREAD

**Issue by gudvinr** [Zuzu-Typ/PyOgg#3]
Besides already implemented `libopusfile`/`libvorbisfile` there is [libopusenc](https://github.com/xiph/libopusenc) and [libvorbisenc](https://github.com/xiph/vorbis) (vorbisenc.c/vorbisenc.h) which are high-level helper libraries for encoding opus/vorbis streams.

Is this possible to add bindings for them too?

**Comment by Zuzu-Typ** [comment]
It should now be possible to use both, however I couldn't try them out, so please let me know if there are any issues.
It might crash upon loading libopusenc, because some of the methods are not present in the library.
