### ISSUE TITLE
Working with Vorbis

### ISSUE THREAD

**Issue by stolpa4** [Zuzu-Typ/PyOgg#41]
Hello. @Zuzu-Typ. Thank you for your work, your library is my hope.
I just have a little question.
After successfully opening the .mogg with the VorbisFile class, I don't know what to do with the buffer. How do I decode it? 
Can you share some hints or links on this stuff?

Thank you

**Comment by Zuzu-Typ** [comment]
Hi there @stolpa4 

When you've opened the file, the buffer has already been decoded. The buffer you're left with is the pure audio data -- basically a waveform expressed as byte values, ranging from 0 to 255.

It's really up to you what you wish to do with that data.
You can play it back using a library like [PyAudio](https://pypi.org/project/PyAudio/) (which doesn't have wheels for Python 3.6+ unfortunately) or my other library [PyOpenAL](https://github.com/Zuzu-Typ/PyOpenAL) to play back the sound .
You can also use [PyWave](https://github.com/Zuzu-Typ/PyWave) to save the decompressed audio as `.wav` if you so desire.

It's not super easy to get something like that to work, so don't be too hard on yourself (:

Cheers
--Zuzu_Typ--

**Comment by stolpa4** [comment]
@Zuzu-Typ 
Gorgeous! Thank you for your answer and time, I'll try it out then.
