### ISSUE TITLE
A typo found as well as my suggestion for style

### ISSUE THREAD

**Issue by zhengwx11** [Zuzu-Typ/PyOgg#8]
In File `library_loader.py` at Line 33, there is a variable called `paths` written as `pahts`, which results in uncaught `name xxx not defined` exception.

Note that such typo should be caught by exception. However, it is simply dropped in File `ogg.py` at Line 58. 

** Please at least print out exceptions rather than drop them. **

**Comment by zhengwx11** [comment]
My bad. 
It seems like the pip image is older than your git repo.

**Comment by Zuzu-Typ** [comment]
It was fixed in version [0.6.3a1](https://pypi.org/project/PyOgg/0.6.3a1/) .
Please try running `pip install pyogg --upgrade`

I will however change the way it handles exceptions shortly.
Thank you for your suggestion :)
