### ISSUE TITLE
Problem with read ogg file

### ISSUE THREAD

**Issue by zhengwx11** [Zuzu-Typ/PyOgg#9]
I met another problem when reading ogg file. (with master branch on github this time.)

Simply run:
```
import pyogg
pyogg.VorbisFile('./test.ogg')
```

It turns out:
```
python3: malloc.c:3722: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
Aborted (core dumped)
```

Seems like there is something wrong with memory manipulation in C code, which would be a big trouble.

The ogg file was generated via online recording with Firefox browser. See the attachment.
[test.zip](https://github.com/Zuzu-Typ/PyOgg/files/2133040/test.zip)

Note that it could be converted to wave file by ffmpeg correctly.

**Comment by Zuzu-Typ** [comment]
I don't know why the shown error is thrown, however, the reason why this doesn't work is because your file is not an Ogg Vorbis file.
It's encoded with the Ogg Opus codec.
try `pyogg.OpusFile('./test.ogg')` instead.
